apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-app-deployment
    labels:
        app: todo-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: todo-app
    template:
        metadata:
            labels:
                app: todo-app
        spec:
            containers:
                - name: todo-app
                  image: todo-web-app
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3000
                  env:
                      - name: MONGO_SERVER
                        valueFrom:
                            configMapKeyRef:
                                name: mongo-config
                                key: mongo-server
                      - name: MONGO_DB
                        valueFrom:
                            configMapKeyRef:
                                name: mongo-config
                                key: mongo-db
---
apiVersion: v1
kind: Service
metadata:
    name: todo-app-service
spec:
    type: NodePort
    selector:
        app: todo-app
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 30000
